sonar.host.url=http://host.docker.internal:9000
sonar.projectKey=tasklist-frontend
sonar.projectName=TaskList - Frontend
sonar.projectVersion=1.0.0

sonar.sources=src
sonar.exclusions=src/__tests__/**, node_modules/**, dist/**, vite.config.ts, vitest.config.ts
sonar.tests=src/__tests__
sonar.test.inclusions=src/__tests__/**/*.test.ts, src/__tests__/**/*.test.tsx

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.junit.reportPaths=reports
sonar.sourceEncoding=UTF-8